package com.facemake.dal.mapper;

import com.facemake.dal.pojo.FmUser;
import com.facemake.dal.pojo.FmUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FmUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int countByExample(FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int deleteByExample(FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int insert(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int insertSelective(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	List<FmUser> selectByExampleWithBLOBs(FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	List<FmUser> selectByExample(FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	FmUser selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByExampleSelective(@Param("record") FmUser record,
			@Param("example") FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByExampleWithBLOBs(@Param("record") FmUser record,
			@Param("example") FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByExample(@Param("record") FmUser record,
			@Param("example") FmUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByPrimaryKeySelective(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(FmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	int updateByPrimaryKey(FmUser record);
}