package com.facemake.dal.pojo;

import java.util.Date;

public class FmUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.id
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.nick
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.password
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.come_from
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Boolean comeFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.icon
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.status
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.flag
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Integer flag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.gmt_create
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.gmt_modified
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column fm_user.attributes
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	private String attributes;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.id
	 * @return  the value of fm_user.id
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.id
	 * @param id  the value for fm_user.id
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.nick
	 * @return  the value of fm_user.nick
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.nick
	 * @param nick  the value for fm_user.nick
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setNick(String nick) {
		this.nick = nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.password
	 * @return  the value of fm_user.password
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.password
	 * @param password  the value for fm_user.password
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.come_from
	 * @return  the value of fm_user.come_from
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Boolean getComeFrom() {
		return comeFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.come_from
	 * @param comeFrom  the value for fm_user.come_from
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setComeFrom(Boolean comeFrom) {
		this.comeFrom = comeFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.icon
	 * @return  the value of fm_user.icon
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.icon
	 * @param icon  the value for fm_user.icon
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.status
	 * @return  the value of fm_user.status
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.status
	 * @param status  the value for fm_user.status
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.flag
	 * @return  the value of fm_user.flag
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.flag
	 * @param flag  the value for fm_user.flag
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.gmt_create
	 * @return  the value of fm_user.gmt_create
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.gmt_create
	 * @param gmtCreate  the value for fm_user.gmt_create
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.gmt_modified
	 * @return  the value of fm_user.gmt_modified
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.gmt_modified
	 * @param gmtModified  the value for fm_user.gmt_modified
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column fm_user.attributes
	 * @return  the value of fm_user.attributes
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public String getAttributes() {
		return attributes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column fm_user.attributes
	 * @param attributes  the value for fm_user.attributes
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	public void setAttributes(String attributes) {
		this.attributes = attributes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		FmUser other = (FmUser) that;
		return (this.getId() == null ? other.getId() == null : this.getId()
				.equals(other.getId()))
				&& (this.getNick() == null ? other.getNick() == null : this
						.getNick().equals(other.getNick()))
				&& (this.getPassword() == null ? other.getPassword() == null
						: this.getPassword().equals(other.getPassword()))
				&& (this.getComeFrom() == null ? other.getComeFrom() == null
						: this.getComeFrom().equals(other.getComeFrom()))
				&& (this.getIcon() == null ? other.getIcon() == null : this
						.getIcon().equals(other.getIcon()))
				&& (this.getStatus() == null ? other.getStatus() == null : this
						.getStatus().equals(other.getStatus()))
				&& (this.getFlag() == null ? other.getFlag() == null : this
						.getFlag().equals(other.getFlag()))
				&& (this.getGmtCreate() == null ? other.getGmtCreate() == null
						: this.getGmtCreate().equals(other.getGmtCreate()))
				&& (this.getGmtModified() == null ? other.getGmtModified() == null
						: this.getGmtModified().equals(other.getGmtModified()))
				&& (this.getAttributes() == null ? other.getAttributes() == null
						: this.getAttributes().equals(other.getAttributes()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table fm_user
	 * @mbggenerated  Thu Jul 24 01:18:59 CST 2014
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
		result = prime * result
				+ ((getNick() == null) ? 0 : getNick().hashCode());
		result = prime * result
				+ ((getPassword() == null) ? 0 : getPassword().hashCode());
		result = prime * result
				+ ((getComeFrom() == null) ? 0 : getComeFrom().hashCode());
		result = prime * result
				+ ((getIcon() == null) ? 0 : getIcon().hashCode());
		result = prime * result
				+ ((getStatus() == null) ? 0 : getStatus().hashCode());
		result = prime * result
				+ ((getFlag() == null) ? 0 : getFlag().hashCode());
		result = prime * result
				+ ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
		result = prime
				* result
				+ ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
		result = prime * result
				+ ((getAttributes() == null) ? 0 : getAttributes().hashCode());
		return result;
	}
}